// <auto-generated />
using System;
using HealthPilot.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthPilot.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306182537_AddNegotiatedRatePolicyMetadata")]
    partial class AddNegotiatedRatePolicyMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthPilot.Api.Models.CashPrice", b =>
                {
                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CashPriceAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cash_price");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProcedureId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("ProcedureId", "FacilityId");

                    b.ToTable("cash_prices", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.EstimateAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BenefitLogicVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("CoinsurancePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Copay")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("CopayAppliesBeforeDeductible")
                        .HasColumnType("boolean");

                    b.Property<string>("CptCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeductibleRemaining")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("EstimatedPatientResponsibility")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Insurer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("InsurerPayment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("NegotiatedRateUsed")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("OopMaxRemaining")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TraceId");

                    b.HasIndex("ZipCode", "Insurer", "CptCode");

                    b.ToTable("estimate_audit_logs", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Zip");

                    b.HasIndex("Name", "City", "State", "Zip")
                        .IsUnique();

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.IngestionCheckpoint", b =>
                {
                    b.Property<string>("CheckpointKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("RowsProcessed")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CheckpointKey");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("ingestion_checkpoints", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.IngestionJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<string>("CheckpointKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("FileHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RecordsReceived")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("integer");

                    b.Property<long?>("ReplayOfJobId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ResumeFromCheckpoint")
                        .HasColumnType("boolean");

                    b.Property<int>("RowsProcessed")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FileHashSha256");

                    b.HasIndex("ReplayOfJobId");

                    b.HasIndex("Status");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.Insurer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("insurers", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.NegotiatedRate", b =>
                {
                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<int>("InsurerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EffectiveEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProcedureId", "FacilityId", "InsurerId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("InsurerId");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("EffectiveStartUtc", "EffectiveEndUtc");

                    b.HasIndex("ProcedureId", "InsurerId", "FacilityId");

                    b.ToTable("negotiated_rates", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CptCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CptCode")
                        .IsUnique();

                    b.ToTable("procedures", (string)null);
                });

            modelBuilder.Entity("HealthPilot.Api.Models.CashPrice", b =>
                {
                    b.HasOne("HealthPilot.Api.Models.Facility", "Facility")
                        .WithMany("CashPrices")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPilot.Api.Models.Procedure", "Procedure")
                        .WithMany("CashPrices")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("HealthPilot.Api.Models.NegotiatedRate", b =>
                {
                    b.HasOne("HealthPilot.Api.Models.Facility", "Facility")
                        .WithMany("NegotiatedRates")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPilot.Api.Models.Insurer", "Insurer")
                        .WithMany("NegotiatedRates")
                        .HasForeignKey("InsurerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPilot.Api.Models.Procedure", "Procedure")
                        .WithMany("NegotiatedRates")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Insurer");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("HealthPilot.Api.Models.Facility", b =>
                {
                    b.Navigation("CashPrices");

                    b.Navigation("NegotiatedRates");
                });

            modelBuilder.Entity("HealthPilot.Api.Models.Insurer", b =>
                {
                    b.Navigation("NegotiatedRates");
                });

            modelBuilder.Entity("HealthPilot.Api.Models.Procedure", b =>
                {
                    b.Navigation("CashPrices");

                    b.Navigation("NegotiatedRates");
                });
#pragma warning restore 612, 618
        }
    }
}
